CREATE DATABASE `demo`;

CREATE TABLE IF NOT EXISTS demo.`tasks`(
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `creation_date` VARCHAR(45) NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  `modified_date` VARCHAR(45) NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  PRIMARY KEY (`id`)
);